### ISSUE TITLE
running fab quickstart <path-to-pcap-file> results in error (data branch)

### ISSUE THREAD

**Issue by charlesporter** [OpenSOC/opensoc-vagrant#8]
README.md in data branch suggests running fab quickstart with a path to a pcap file
This causes an error causes  error

```
$fab vagrant quickstart /work/opensoc/opensoc-vagrant/resources/opensoc.pcap

Warning: Command(s) not found:
    /work/opensoc/opensoc-vagrant/resources/opensoc.pcap
```

**Comment by tpiscitell** [comment]
Ahh thats a silly typo in the README. you pass parameters to fabric tasks using a colon, not spaces. Thanks for catching it. Also FYI this feature may not work just quite yet. Has not been tested as you can probably infer from this typo....

**Comment by charlesporter** [comment]
as anticipated by you: with colon instead of space, get a new error: 
$ fab vagrant quickstart:/work/opensoc/opensoc-vagrant/resources/opensoc.pcap 
[localhost] local: vagrant ssh-config
[localhost] local: vagrant status | grep node | wc -l
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Fabric-1.10.2-py2.7.egg/fabric/main.py", line 743, in main
    _args, *_kwargs
  File "/Library/Python/2.7/site-packages/Fabric-1.10.2-py2.7.egg/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(_args, *_new_kwargs)
  File "/Library/Python/2.7/site-packages/Fabric-1.10.2-py2.7.egg/fabric/tasks.py", line 174, in run
    return self.wrapped(_args, *_kwargs)
TypeError: quickstart() takes no arguments (1 given)

**Comment by BlondAngel** [comment]
Also, when I look into the fabfile.py file, I do not see how the pcap file is passed on from the fab command line to fabfile.py when using the quickstart function.  
I think it is meant to be just like this:
fab vagrant quickstart

**Comment by tpiscitell** [comment]
I'm not sure what I was thinking in my previous comment. This features is not done being developed yet. It was more than just a typo away from being done. Until this features shows up in master I wouldn't expect it to work.
